apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vpngateways.awsvpn.openshift.io
spec:
  group: awsvpn.openshift.io
  names:
    kind: VpnGateway
    listKind: VpnGatewayList
    plural: vpngateways
    singular: vpngateway
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          properties:
            phase:
              description: Phase is the current status of the VPN Gateway
              enum:
              - Creating
              - Detached
              - Ready
              type: string
            vpcID:
              description: VpcID is the AWS ID of the VPC that the VPN Gateway is
                attempting to attach to
              type: string
            vpnGatewayID:
              description: VpnGatewayID is the AWS ID of the VPN Gateway object
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
