apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-vpn-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-vpn-operator
  template:
    metadata:
      labels:
        name: aws-vpn-operator
    spec:
      serviceAccountName: aws-vpn-operator
      containers:
        - name: aws-vpn-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - aws-vpn-operator
          imagePullPolicy: Always
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-vpn-operator-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-vpn-operator-credentials
                  key: aws_secret_access_key
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "aws-vpn-operator"
